---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myingress-canary
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/canary: "true"
      nginx.ingress.kubernetes.io/canary-by-header: "canary"
      nginx.ingress.kubernetes.io/canary-by-header-value: "true"
      # nginx.ingress.kubernetes.io/canary-weight: '50'

    #canary-weight: '10'
    #canary-by-cookie: tester
spec:
  rules:
     - host: canary.softpro.site
       http:
        paths:
          - path: /
            backend:
              serviceName: myapp-canary
              servicePort: 80
