---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myingress-stable
  annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
     - host: canary.softpro.site
       http:
        paths:
          - path: /
            backend:
              serviceName: myapp-stable
              servicePort: 80
