apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
     name: carol
subjects:
  - kind: Group
    name: system:serviceaccounts
roleRef:
    kind: Role
    name: carol
    apiGroup: rbac.authorization.k8s.io